name: IT

on:
  - push
  - workflow_dispatch

jobs:
  it:
    runs-on: ubuntu-latest

    container: ubuntu:22.04
    services:
      lila:
        image: ghcr.io/lichess-org/lila-docker:main
        options: --restart=always

    steps:
      - uses: actions/checkout@v4
        with:
          ref: main
          path: chariot

      - name: Install curl
        run: apt-get update && apt-get install -y curl

      - name: Download OpenJDK 22
        run: |
          download_url="https://download.java.net/java/GA/jdk22/830ec9fcccef480bb3e73fb7ecafe059/36/GPL/openjdk-22_linux-x64_bin.tar.gz"
          curl -Lo $RUNNER_TEMP/java_package.tar.gz $download_url

      - uses: actions/setup-java@v4
        with:
          distribution: 'jdkfile'
          jdkFile: ${{ runner.temp }}/java_package.tar.gz
          java-version: '22'
          architecture: x64

      - name: Check java version
        run: java -Xinternalversion

      - name: Run integration tests
        run: cd chariot && java build/Build.java
        env:
          LILA_API: http://lila:9663
          IT_LONG: y
          CLEANUP: y
